#include QMK_KEYBOARD_H

// Colemak DH Homerow mods
#define GUI_C_L LGUI_T(KC_A)
#define ALT_C_L LALT_T(KC_R)
#define CTL_C_L LCTL_T(KC_S)
#define SFT_C_L LSFT_T(KC_T)
#define SFT_C_R RSFT_T(KC_N)
#define CTL_C_R RCTL_T(KC_E)
#define ALT_C_R RALT_T(KC_I)
#define GUI_C_R RGUI_T(KC_O)

// QWERTY Homerow mods
#define GUI_Q_L LGUI_T(KC_A)
#define ALT_Q_L LALT_T(KC_S)
#define CTL_Q_L LCTL_T(KC_D)
#define SFT_Q_L LSFT_T(KC_F)
#define SFT_Q_R RSFT_T(KC_J)
#define CTL_Q_R RCTL_T(KC_K)
#define ALT_Q_R RALT_T(KC_L)
#define GUI_Q_R RGUI_T(KC_SCLN)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT( // Colemak
		KC_Q,    KC_W,    KC_F,    KC_P,    KC_B,    KC_J,    KC_L,    KC_U,    KC_Y,    KC_SCLN,
		GUI_C_L, ALT_C_L, CTL_C_L, SFT_C_L, KC_G,    KC_M,    SFT_C_R, CTL_C_R, ALT_C_R, GUI_C_R,
		KC_Z,    KC_X,    KC_C,    KC_D,    KC_V,    KC_K,    KC_H,    KC_COMM, KC_DOT,  KC_SLSH,

		LT(2,KC_ESC),
		LT(3,KC_SPC),
		LT(4,KC_ENT),
		LT(5,KC_BSPC)
	),
	[2] = LAYOUT( // Nav
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_DOWN, KC_RGHT, KC_PGUP, XXXXXXX, XXXXXXX,
		KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, XXXXXXX, XXXXXXX, KC_LBRC, KC_RBRC, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_UP,   KC_LEFT, KC_PGDN, XXXXXXX, XXXXXXX,
		                           XXXXXXX, XXXXXXX, KC_LPRN, KC_RPRN
	),
	[3] = LAYOUT( // Symbols
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_AT,   KC_EXLM, KC_HASH, KC_PERC, KC_CIRC,
		KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, XXXXXXX, KC_EQL,  KC_PLUS, KC_MINS, KC_ASTR, KC_BSLS,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_AMPR, KC_QUES, KC_QUOT, KC_GRV,  KC_DLR,
		                           XXXXXXX, XXXXXXX, KC_UNDS, KC_DEL
	),
	[4] = LAYOUT( // Numbers
		XXXXXXX, KC_7,    KC_8,    KC_9,    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, KC_4,    KC_5,    KC_6,    XXXXXXX, XXXXXXX, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI,
		XXXXXXX, KC_1,    KC_2,    KC_3,    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,

		LT(6,KC_0),
		KC_TAB,
		XXXXXXX,
		XXXXXXX
	),
	[5] = LAYOUT( // System
		QK_BOOT, KC_BTN1, KC_MS_U, KC_BTN2, KC_WH_U, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, KC_MS_L, KC_MS_D, KC_MS_R, KC_WH_D, XXXXXXX, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		                           DF(7),   KC_CAPS, XXXXXXX, XXXXXXX
	),
	[6] = LAYOUT( // F Keys
		XXXXXXX, KC_F7,   KC_F8,   KC_F9,   KC_F10,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, KC_F4,   KC_F5,   KC_F6,   KC_F11,  XXXXXXX, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI,
		XXXXXXX, KC_F1,   KC_F2,   KC_F3,   KC_F12,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		                           XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX
	),
	[7] = LAYOUT( // Gaming
		KC_ESC,  KC_Q,    KC_W,    KC_E,    KC_R,    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		KC_TAB,  KC_A,    KC_S,    KC_D,    KC_F,    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		KC_LCTL, KC_Z,    KC_X,    KC_C,    KC_V,    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		                           KC_LSFT, KC_SPC,  DF(0),   XXXXXXX
	),
};
